# Generated by Django 3.2 on 2021-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_tb',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='products_tb',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='products_tb',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='products_tb',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='products_tb',
            name='product_image_main',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
