# Generated by Django 3.2 on 2021-05-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0002_auto_20210501_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_tb',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
